@url = http://localhost:3017

### Api Docs
GET {{url}}

### Get Data
GET {{url}}/data

### Get Routes
{{url}}/routes

### Get Route
{{url}}/routes/63e84155b6b5d0a37c3d4f6c

### Delete Route
DELETE {{url}}/routes/63e85fb14f287cc02cba1ee5

### Add Route
POST {{url}}/routes
content-type: application/json

{
    "name": "portfoliodddddddddddddddddd",
    "source" : "https://portfolio-navy-two-14.vercel.app/welcome"
}

### EDIT Route
PUT {{url}}/routes/63e85fb14f287cc02cba1ee5
content-type: application/json

{
"name": "projectvvvvvvvv",
"source": "https://www.xing.com/profile/Mohammad_Amaren/cv"
}

### Pad login
POST {{url}}/login
content-type: application/json

{
    "password": "badPassword"
}

### Good login
POST {{url}}/login
content-type: application/json

{
    "password": "###"
}

### Get current user
{{url}}/get-current-user

### Logout
{{url}}/logout